"""add_map_position_to_users

Revision ID: 448e5351a921
Revises: d2d6a6d1b5dd
Create Date: 2026-04-21 12:14:55.131604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '448e5351a921'
down_revision: Union[str, Sequence[str], None] = 'd2d6a6d1b5dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seed_users')
    op.add_column('users', sa.Column('map_x', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('map_y', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'map_y')
    op.drop_column('users', 'map_x')
    op.create_table('seed_users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('excerpt', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('themes', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=False),
    sa.Column('camp', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('embedding', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('map_x', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('map_y', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('seed_users_pkey'))
    )
    # ### end Alembic commands ###
